### ISSUE TITLE
types of switches

### ISSUE THREAD

**Issue by shiftux** [abstracthat/dactyl-manuform#3]
hello, 
this project looks amazing! thanks for all the work! - i'm planning on making one!
i'd like to understand the compatibility with different switch manufacturers... 
thinking of Cherry, Kailh, Gateron, ...
Could someone make a statement about what would fit?
or is it possible to customize the switch sockets (like explained here https://github.com/adereth/dactyl-keyboard/issues/56#issuecomment-376463735) ? 

thanks for your insights

**Comment by BobLoblaw5** [comment]
I just built one using gateron browns and I know cherry switches will work as well.  Not as familiar with Kailh but I would think that any Mx style switch should work.

**Comment by shiftux** [comment]
the answer here is yes, they do work. 
but indeed you need to modify the switch sockets, you'll want to remove the "side-nub" in the clojure files
